parameters:
    pim_magento_connector.manager.locale.class:              Pim\Bundle\MagentoConnectorBundle\Manager\LocaleManager
    pim_magento_connector.manager.currency.class:            Pim\Bundle\MagentoConnectorBundle\Manager\CurrencyManager
    pim_magento_connector.manager.category_mapping.class:    Pim\Bundle\MagentoConnectorBundle\Manager\CategoryMappingManager
    pim_magento_connector.manager.family_mapping.class:      Pim\Bundle\MagentoConnectorBundle\Manager\FamilyMappingManager
    pim_magento_connector.manager.group_mapping.class:       Pim\Bundle\MagentoConnectorBundle\Manager\AttributeGroupMappingManager
    pim_magento_connector.manager.attribute_mapping.class:   Pim\Bundle\MagentoConnectorBundle\Manager\AttributeMappingManager
    pim_magento_connector.manager.simple_mapping.class:      Pim\Bundle\MagentoConnectorBundle\Manager\SimpleMappingManager
    pim_magento_connector.manager.association_type.class:    Pim\Bundle\MagentoConnectorBundle\Manager\AssociationTypeManager
    pim_magento_connector.manager.product_value.class:       Pim\Bundle\MagentoConnectorBundle\Manager\ProductValueManager
    pim_magento_connector.manager.attribute.class:           Pim\Bundle\MagentoConnectorBundle\Manager\AttributeManager
    pim_magento_connector.manager.group.class:               Pim\Bundle\MagentoConnectorBundle\Manager\GroupManager
    pim_magento_connector.manager.product_export.class:      Pim\Bundle\MagentoConnectorBundle\Manager\ProductExportManager
    pim_magento_connector.manager.simple_mapping.class:      Pim\Bundle\MagentoConnectorBundle\Manager\SimpleMappingManager
    pim_magento_connector.manager.configurable_export.class: Pim\Bundle\MagentoConnectorBundle\Manager\ConfigurableExportManager

services:
    # overriden PIM managers
    pim_magento_connector.manager.association_type:
        class: %pim_magento_connector.manager.association_type.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - %pim_catalog.entity.association_type.class%

    pim_magento_connector.manager.product_value:
        class: %pim_magento_connector.manager.product_value.class%
        arguments:
            - %pim_catalog.entity.product_value.class%

    pim_magento_connector.manager.group:
        class: %pim_magento_connector.manager.group.class%
        arguments:
            - '@pim_catalog.manager.group'
            - '@pim_magento_connector.repository.group'

    pim_magento_connector.manager.locale:
        class: %pim_magento_connector.manager.locale.class%
        arguments:
            - '@pim_catalog.manager.locale'

    pim_magento_connector.manager.currency:
        class: %pim_magento_connector.manager.currency.class%
        arguments:
            - '@pim_catalog.manager.currency'

    pim_magento_connector.manager.attribute:
        class: %pim_magento_connector.manager.attribute.class%
        arguments:
            - '@pim_catalog.manager.attribute'
            - '@doctrine.orm.entity_manager'
            - %pim_catalog.entity.attribute.class%

    # mapping managers
    pim_magento_connector.manager.category_mapping:
        class: %pim_magento_connector.manager.category_mapping.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - %pim_magento_connector.entity.category_mapping.class%

    pim_magento_connector.manager.family_mapping:
        class: %pim_magento_connector.manager.family_mapping.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - %pim_magento_connector.entity.family_mapping.class%

    pim_magento_connector.manager.group_mapping:
        class: %pim_magento_connector.manager.group_mapping.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - %pim_magento_connector.entity.group_mapping.class%

    pim_magento_connector.manager.attribute_mapping:
        class: %pim_magento_connector.manager.attribute_mapping.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - %pim_magento_connector.entity.attribute_mapping.class%

    pim_magento_connector.manager.simple_mapping:
        class: %pim_magento_connector.manager.simple_mapping.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - %pim_magento_connector.entity.simple_mapping.class%

    # delta entities managers
    pim_magento_connector.manager.product_export:
        class: %pim_magento_connector.manager.product_export.class%
        arguments:
            - @doctrine.orm.entity_manager
            - %pim_magento_connector.entity.delta_product_export.class%
            - %pim_catalog.entity.product.class%

    pim_magento_connector.manager.product_value_export:
        parent: pim_magento_connector.manager.product_export
        arguments:
            - true

    pim_magento_connector.manager.configurable_export:
        class: %pim_magento_connector.manager.configurable_export.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - %pim_magento_connector.entity.delta_configurable_export.class%
            - %pim_catalog.entity.group.class%
