parameters:
    pim_magento_connector.processor.product.class: Pim\Bundle\MagentoConnectorBundle\Processor\ProductProcessor
    pim_magento_connector.processor.configurable.class: Pim\Bundle\MagentoConnectorBundle\Processor\ConfigurableProcessor
    pim_magento_connector.processor.product_association.class: Pim\Bundle\MagentoConnectorBundle\Processor\ProductAssociationProcessor
    pim_magento_connector.processor.category.class: Pim\Bundle\MagentoConnectorBundle\Processor\CategoryProcessor
    pim_magento_connector.processor.attribute.class: Pim\Bundle\MagentoConnectorBundle\Processor\AttributeProcessor
    pim_magento_connector.processor.option.class: Pim\Bundle\MagentoConnectorBundle\Processor\OptionProcessor

services:
    # processors
    pim_magento_connector.processor.product:
        class: %pim_magento_connector.processor.product.class%
        arguments:
            - '@pim_magento_connector.guesser.magento_webservice'
            - '@pim_magento_connector.guesser.magento_normalizer'
            - '@pim_magento_connector.manager.locale'
            - '@pim_magento_connector.merger.storeview_mapping'
            - '@pim_magento_connector.manager.currency'
            - '@pim_catalog.manager.channel'
            - '@pim_magento_connector.merger.category_mapping'
            - '@pim_transform.converter.metric'
            - '@pim_magento_connector.manager.association_type'
    pim_magento_connector.processor.configurable:
        class: %pim_magento_connector.processor.configurable.class%
        arguments:
            - '@pim_magento_connector.guesser.magento_webservice'
            - '@pim_magento_connector.guesser.magento_normalizer'
            - '@pim_magento_connector.manager.locale'
            - '@pim_magento_connector.merger.storeview_mapping'
            - '@pim_magento_connector.manager.currency'
            - '@pim_catalog.manager.channel'
            - '@pim_magento_connector.merger.category_mapping'
            - '@pim_magento_connector.manager.group'
    pim_magento_connector.processor.product_association:
        class: %pim_magento_connector.processor.product_association.class%
        arguments:
            - '@pim_magento_connector.guesser.magento_webservice'
            - '@pim_magento_connector.guesser.magento_normalizer'
            - '@pim_magento_connector.manager.locale'
            - '@pim_magento_connector.merger.storeview_mapping'
            - '@pim_magento_connector.manager.association_type'

    pim_magento_connector.processor.category:
        class: %pim_magento_connector.processor.category.class%
        arguments:
            - '@pim_magento_connector.guesser.magento_webservice'
            - '@pim_magento_connector.guesser.magento_normalizer'
            - '@pim_magento_connector.manager.locale'
            - '@pim_magento_connector.merger.storeview_mapping'
            - '@pim_magento_connector.merger.category_mapping'

    pim_magento_connector.processor.attribute:
        class: %pim_magento_connector.processor.attribute.class%
        arguments:
            - '@pim_magento_connector.guesser.magento_webservice'
            - '@pim_magento_connector.guesser.magento_normalizer'
            - '@pim_magento_connector.manager.locale'
            - '@pim_magento_connector.merger.storeview_mapping'
            - '@pim_magento_connector.merger.attribute_mapping'
    pim_magento_connector.processor.option:
        class: %pim_magento_connector.processor.option.class%
        arguments:
            - '@pim_magento_connector.guesser.magento_webservice'
            - '@pim_magento_connector.guesser.magento_normalizer'
            - '@pim_magento_connector.manager.locale'
            - '@pim_magento_connector.merger.storeview_mapping'
